### ISSUE TITLE
Lowered requirements?

### ISSUE THREAD

**Issue by pschuegr** [mblum14/rspec-profiler#1]
Hi,

Can I ask why you lowered the rspec requirements to 2.8?

Thanks!

**Comment by mblum14** [comment]
If I recall correctly, I originally was testing with rspec version 2.11 and was slowly testing earlier versions of rspec to see if my code would work with them. I believe I stopped testing at rspec version 2.8 (I don't recall if I tested with earlier versions or not). It should work with later versions though.

**Comment by pschuegr** [comment]
Ah thanks.  I'll try and test with 2.9 if I have a chance.
